dist: bionic
before_install:
  - sudo apt-get -y install racket racket-doc

install:
 - make deps


jobs:
  include:
    - stage: "Build"
      name: "Build"
      script: "make build_unix"
    - stage: "Test"
      name: "Test"
      script: "make test"